// <auto-generated />
using System;
using DemoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApi.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20240816174025_TlmApps_add")]
    partial class TlmApps_add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoApi.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("EmployeeGenderId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeGenderId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DemoApi.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("DemoApi.Models.TlmApp", b =>
                {
                    b.Property<string>("TJX_App_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("App_Accessability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_Authentication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_Defined_Responsiveness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("App_Initial_Deploy_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("App_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_Performance_Satisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_Support_Team")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("App_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Architecture_contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Automation_Deployment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_Capabilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_Criticality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COTS_Customization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentation_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentation_Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("External_Vendor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Functional_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Future_Scalability")
                        .HasColumnType("int");

                    b.Property<string>("Integration_protocol_list")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeanIX_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leanix_TJX_APP_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legacy_TJX_APP_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legal_Requirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Multi_Lingual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_Inbound_Interfaces")
                        .HasColumnType("int");

                    b.Property<int>("Num_Outbound_Interfaces")
                        .HasColumnType("int");

                    b.Property<int>("Num_Screens")
                        .HasColumnType("int");

                    b.Property<int>("Num_interfaces")
                        .HasColumnType("int");

                    b.Property<string>("Peak_period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qtly_Release_Frequency")
                        .HasColumnType("int");

                    b.Property<string>("SNOW_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security_Enablement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sensitive_Data_Applicable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill_Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Software_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solution_Delivery_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source_code_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_Party_Dependency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Interface_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("app_owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compliance_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_updated_date")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TJX_App_ID");

                    b.ToTable("TlmApps");
                });

            modelBuilder.Entity("DemoApi.Models.Employee", b =>
                {
                    b.HasOne("DemoApi.Models.Gender", "EmployeeGender")
                        .WithMany()
                        .HasForeignKey("EmployeeGenderId");

                    b.Navigation("EmployeeGender");
                });
#pragma warning restore 612, 618
        }
    }
}
